[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# K8s Cluster

## Master Node

### kube\-api\-server

#### etcd

### kube\-scheduler

### kube\-controller\-manager

### cloud controller manager

## Worker Node

### kubelet

### kube\-proxy

#### kube\-proxy supported mode<br/>User space mode<br/>Iptables mode<br/>IPVS mode<br/><br/>redirect traffic by randomly pick backend pod
> align=`left`


### CRI

#### pods
